# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  # Box Setting
  #config.vm.box = "centos/7"


  # Provider Settings
  # config.vm.provider "virtualbox" do |vb|
  #   vb.memory = 2048
  #   vb.cpus = 4

  # end
 
  #Network Settings
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"



  config.vm.define "master1" do |master1|
    master1.ssh.insert_key = false
    master1.vm.hostname = "master1"
    master1.vm.network "private_network", ip: "192.168.33.10"
    master1.vm.box = "bento/centos-7.2"
    config.vm.provision "file", source: "/Users/manpreetsingh/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
  end

end

