---
# tasks file for kafka

- name: Yum - Update instance
  yum:
    name: "*"
    state: latest
    update_only: yes

- name: Yum - Install Dependency
  yum:
    name:
        - git
        - wget
        - go
        - telnet


- name: Command - Enable Java Dependacy
  command: /usr/bin/amazon-linux-extras enable corretto8

- name: Yum - Install Java Dependency
  yum:
    name: java-1.8.0-amazon-corretto
    state: present

- name: Stat - Kafka file
  stat:
    path: /home/ec2-user/kafka_2.13-2.7.0.tgz
  register: kafaFile

- name: Get_Url - DownLoad Kafka
  get_url:
    url: https://mirror.olnevhost.net/pub/apache/kafka/2.7.0/kafka_2.13-2.7.0.tgz
    dest: /home/ec2-user
  when: kafaFile.stat.exists == False

- name: Command - Extract Kafka file
  command:
    cmd: /usr/bin/tar -xvf kafka_2.13-2.7.0.tgz
    chdir: /home/ec2-user
  when: kafaFile.stat.exists == False

- name: Command -- Create the neccessary directory
  command:
    cmd: /usr/bin/mkdir -p data/kafka-data/zookeeper
    chdir: /home/ec2-user/kafka_2.13-2.7.0/

- name: Line_in_File -- Modifying the server.properties log.dirs
  lineinfile:
    path: /home/ec2-user/kafka_2.13-2.7.0/config/server.properties
    regexp: '^log.dirs='
    line: log.dirs=/home/ec2-user/kafka_2.13-2.7.0/data/kafka
  notify:
    Restart Kafka Service


- name: Line_in_File - zookeeper host string
  lineinfile:
    path: /home/ec2-user/kafka_2.13-2.7.0/config/server.properties
    regexp: '^zookeeper.connect='
    line: zookeeper.connect=10.12.2.110:2181
  notify:
    - Restart Kafka Service

- name: Line_in_File -- Modifying the server.properties
  lineinfile:
    path: /home/ec2-user/kafka_2.13-2.7.0/config/server.properties
    regexp: '^#listeners=PLAINTEXT'
    line: listeners=PLAINTEXT://0.0.0.0:{{listener_num}}
  notify:
    - Restart Kafka Service

- name: Line_in_File -- Broker Id for server
  lineinfile:
    path: /home/ec2-user/kafka_2.13-2.7.0/config/server.properties
    regexp: '^broker.id=0'
    line: broker.id={{broker_num}}

- name: Copy - Kafka Service 
  copy:
    src: kafka.service
    dest: /etc/systemd/system/kafka.service
  notify:
    - Daemon Reload
    - Restart kafka Service


