- hosts: zookeeper
  become: yes
  become_user: root
  roles:
    - role: './roles/zookeeper'

- hosts: kafka
  become: yes
  become_user: root
  roles:
    - role: './roles/kafka/'
  environment:
    GOPATH: "/home/ec2-user/go"

- hosts: webserver1
  become: yes
  become_user: root
  roles:
    - role: './roles/webservers/'
  vars:
    webserver_num: 1

# - hosts: webserver2
#   become: yes
#   become_user: root
#   roles:
#     - role: './roles/webservers/'
#   vars:
#     webserver_num: 2

# - hosts: webserver3
#   become: yes
#   become_user: root
#   roles:
#     - role: './roles/webservers/'
#   vars:
#     webserver_num: 3

# - hosts: bastion
#   become: yes
#   become_user: root
#   roles:
#     - role: './roles/bastion/'