---
# handlers file for webservers

- name: Reload Daemons
  command: /usr/bin/systemctl daemon-reload
  become: yes
  become_user: root

- name: Build Consumer Go Binary
  command:
    cmd: /usr/bin/go build consumer.go
    chdir: /home/ec2-user/
  become: yes
  become_user: root

- name: Restart Nginx Service
  service:
    name: nginx
    state: restarted

- name: Restart Consumer Service
  service:
    name: consumer
    state: restarted
